
services:
  db:
    image: mysql:5.7
    container_name: ml_model_tracking_db
    restart: always
    environment:
      MYSQL_DATABASE: "wines_database"
      MYSQL_ROOT_PASSWORD: "ale_sql_pass"
      MYSQL_PASSWORD: "ale_sql_pass"
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ale_sql_pass --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  mlflow_db:
    image: mysql:5.7
    container_name: ml_model_tracking_mlflow_db
    restart: always
    environment:
      MYSQL_DATABASE: "mlflow_database"
      MYSQL_ROOT_PASSWORD: "ale_sql_pass"
      MYSQL_PASSWORD: "ale_sql_pass"
    ports:
      - "3308:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ale_sql_pass --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  simulator:
    build: ./microservices/simulator
    container_name: ml_model_tracking_simulator
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  ml:
    build: ./microservices/ml
    container_name: ml_model_tracking_ml
    ports:
      - "5001:5001"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  tracking:
    build: ./microservices/tracking
    container_name: ml_model_tracking_tracking
    ports:
      - "5002:5002"
    links:
      - db
      - mlflow_db
    depends_on:
      db:
        condition: service_healthy
      mlflow_db:
        condition: service_healthy

  monitoring:
    build: ./microservices/monitoring
    container_name: ml_model_monitoring_monitoring
    ports:
      - "5003:5003"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

