general:
  seed: 42

model:

service:

controller:
  app:
    host: "0.0.0.0"
    port: 5001
    debug: False
    base_url: "/root"
    service_url: "/ml"
  db:
    host: "db"
    port: 3306
    name: "wines_database"
    user: "root"
    password: "ale_sql_pass"

